name = "Margins"
uuid = "883ce5cb-1d42-4db9-84e7-eea888f0a17e"
keywords = ["marginal-effects", "econometrics", "statistics", "regression", "glm", "predictions", "linear-models", "average-marginal-effects", "contrasts", "statistical-modeling"]
license = "MIT"
authors = ["Eric Martin Feltham <eric.feltham@aya.yale.edu>"]
categories = ["Statistics", "Sociology", "Econometrics", "Political Science", "Psychology"]
description = "Marginal effects and adjusted predictions for statistical models in Julia"
homepage = "https://github.com/emfeltham/Margins.jl"
version = "2.0.3"

[deps]
CategoricalArrays = "324d7699-5711-5eae-9e2f-1d82baa6b597"
CovarianceMatrices = "60f91f6f-d783-54cb-84f9-544141854719"
DataFrames = "a93c6f00-e57d-5684-b7b6-d8193f3e46c0"
Dates = "ade2ca70-3891-5945-98fb-dc099432e06a"
Distributions = "31c24e10-a181-5473-b8eb-7969acd0382f"
FormulaCompiler = "72341345-62c2-4039-9674-a84f8dcc444c"
GLM = "38e38edf-8417-5370-95a0-9cbb8c7f171a"
LinearAlgebra = "37e2e46d-f89d-539d-b4ee-838fcccc9c8e"
Printf = "de0858da-6303-5e67-8744-51eddeeeb8d7"
Statistics = "10745b16-79ce-11e8-11f9-7d13ad32a3b2"
StatsBase = "2913bbd2-ae8a-5f71-8c99-4fb6c76f3a91"
StatsModels = "3eaba693-59b7-5ba5-a881-562e759f1c8d"
Tables = "bd369af6-aec1-5ad0-b16a-f7cc5008161c"

[compat]
CategoricalArrays = "0.10"
CovarianceMatrices = "0.22"
DataFrames = "1.7"
Dates = "1"
Distributions = "0.25"
FormulaCompiler = "1"
GLM = "1.9"
LinearAlgebra = "1"
Printf = "1"
Statistics = "1"
StatsBase = "0.33, 0.34"
StatsModels = "0.7"
Tables = "1.12"
julia = "1.10"

[extras]
BenchmarkTools = "6e4b80f9-dd63-53aa-95a3-0cdb28fa8baf"
Documenter = "e30172f5-a6a5-5a46-863b-614d45cd2de4"
Random = "9a3f8284-a2c9-5f02-9a11-845980a1fd5c"
Revise = "295af30f-e4ad-537b-8983-00126c2a3abe"
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[targets]
test = ["Test", "Random", "BenchmarkTools"]
